/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminAgendamentosRouteImport } from './routes/admin.agendamentos'
import { Route as AdminBloqueiosRouteImport } from './routes/admin.bloqueios'
import { Route as AdminDisponibilidadeRouteImport } from './routes/admin.disponibilidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendamentosRoute = AdminAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBloqueiosRoute = AdminBloqueiosRouteImport.update({
  id: '/bloqueios',
  path: '/bloqueios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisponibilidadeRoute = AdminDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/bloqueios': typeof AdminBloqueiosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/bloqueios': typeof AdminBloqueiosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/agendamentos': typeof AdminAgendamentosRoute
  '/admin/bloqueios': typeof AdminBloqueiosRoute
  '/admin/disponibilidade': typeof AdminDisponibilidadeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/bloqueios'
    | '/admin/disponibilidade'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/login'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/bloqueios'
    | '/admin/disponibilidade'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendar'
    | '/login'
    | '/admin/agenda'
    | '/admin/agendamentos'
    | '/admin/bloqueios'
    | '/admin/disponibilidade'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agendamentos': {
      id: '/admin/agendamentos'
      path: '/agendamentos'
      fullPath: '/admin/agendamentos'
      preLoaderRoute: typeof AdminAgendamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bloqueios': {
      id: '/admin/bloqueios'
      path: '/bloqueios'
      fullPath: '/admin/bloqueios'
      preLoaderRoute: typeof AdminBloqueiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disponibilidade': {
      id: '/admin/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/admin/disponibilidade'
      preLoaderRoute: typeof AdminDisponibilidadeRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAgendamentosRoute: typeof AdminAgendamentosRoute
  AdminBloqueiosRoute: typeof AdminBloqueiosRoute
  AdminDisponibilidadeRoute: typeof AdminDisponibilidadeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAgendamentosRoute: AdminAgendamentosRoute,
  AdminBloqueiosRoute: AdminBloqueiosRoute,
  AdminDisponibilidadeRoute: AdminDisponibilidadeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendarRoute: AgendarRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
